import {
  AlertTriangle,
  BookOpen,
  Building2,
  CalendarRange,
  CheckCircle2,
  Clock3,
  GitBranchPlus,
  Layers3,
  MapPin,
  Plus,
  Users,
} from "lucide-react";
import type { TeachingWorkspaceConfig } from "./TeachingWorkspacePage";

const sectionLabel = "Teaching Operations";

export const teachingAssignmentsConfig: TeachingWorkspaceConfig = {
  sectionLabel,
  title: "Teaching assignments",
  description:
    "Coordinate LIC ownership, lecturers, and lab support inside the same faculty-style admin workspace used across updated academic setup screens.",
  visibleDescription: "Showing the current assignment lanes prepared for the teaching rollout.",
  actionLabel: "Open Assignment Brief",
  actionIcon: Plus,
  searchPlaceholder: "Search by module, coordinator, or lecturer",
  filterLabel: "Assignment status",
  filterOptions: [
    { label: "All statuses", value: "" },
    { label: "Finalized", value: "FINALIZED" },
    { label: "Review", value: "REVIEW" },
    { label: "Draft", value: "DRAFT" },
  ],
  highlights: [
    "LIC ownership, lecturer coverage, and lab support remain visible in one review lane.",
    "Conflict-heavy assignments stay separated so workload and timing checks are easy to scan.",
    "The page is now aligned with the Faculties surface and ready for future data wiring.",
  ],
  summaryCards: [
    {
      label: "Assignment Packs",
      value: "18",
      detail: "Module offerings staged for teaching ownership and support allocation.",
      tone: "teal",
      icon: BookOpen,
    },
    {
      label: "Finalized Teams",
      value: "12",
      detail: "Ready to publish into timetable and module-offering workflows.",
      tone: "green",
      icon: CheckCircle2,
    },
    {
      label: "Under Review",
      value: "4",
      detail: "Awaiting final workload confirmation or conflict sign-off.",
      tone: "amber",
      icon: Clock3,
    },
    {
      label: "Conflict Alerts",
      value: "2",
      detail: "Open overlap checks still need manual resolution before release.",
      tone: "rose",
      icon: AlertTriangle,
    },
  ],
  rows: [
    {
      id: "assign-csc401",
      category: "FINALIZED",
      title: "CSC401 · Advanced Artificial Intelligence",
      subtitle: "LIC ownership and delivery team confirmed for the primary weekday offering.",
      coverage: "FOC · Level 4 · Term 2 · Weekday",
      coverageMeta: "3 delivery blocks, 1 lab lane, 128 enrolled students.",
      status: "Finalized",
      statusVariant: "success",
      statusMeta: "Conflict checks cleared across timetable, room, and staffing windows.",
      owner: "Dr. N. Perera · 2 lecturers · 1 lab assistant",
      ownerMeta: "Workload spread is balanced against existing semester commitments.",
      checkpoint: "Publish Apr 25, 2026",
      checkpointMeta: "Ready for timetable and LMS synchronization.",
      detailItems: [
        "LIC ownership is aligned to the module moderation and result release flow.",
        "Tutorial coverage includes a backup lecturer for week seven and week eight peaks.",
        "Lab support is reserved for the final three practical assessments.",
      ],
      searchText: "Artificial Intelligence Perera weekday",
    },
    {
      id: "assign-se302",
      category: "REVIEW",
      title: "SE302 · Service Design Studio",
      subtitle: "Shared teaching coverage requires a final sign-off between studio and lecture lanes.",
      coverage: "FOC · Level 3 · Term 1 · Weekend",
      coverageMeta: "2 studio blocks, 1 lecture block, 76 enrolled students.",
      status: "Review",
      statusVariant: "warning",
      statusMeta: "Weekend overlap remains open with a consultation support window.",
      owner: "Ms. R. Jayasekara · 1 lecturer · 2 visiting mentors",
      ownerMeta: "Mentor availability is confirmed, but the lead lecturer slot needs approval.",
      checkpoint: "Sign-off Apr 24, 2026",
      checkpointMeta: "Blocked until workload approval is closed.",
      detailItems: [
        "The lead lecturer still exceeds the preferred weekend contact-hour threshold.",
        "Mentor assignments are ready and tied to the design critique timetable.",
        "A fallback owner has been proposed if the current approval misses the cutoff.",
      ],
      searchText: "Service Design studio weekend Jayasekara",
    },
    {
      id: "assign-is210",
      category: "DRAFT",
      title: "IS210 · Data Warehousing Fundamentals",
      subtitle: "The initial staffing mix is drafted but still waiting for lab support confirmation.",
      coverage: "FOC · Level 2 · Term 1 · Weekday",
      coverageMeta: "2 lecture blocks, 1 lab block, 102 enrolled students.",
      status: "Draft",
      statusVariant: "info",
      statusMeta: "Lab coverage is still provisional until equipment readiness is confirmed.",
      owner: "Mr. K. Fernando · 1 lecturer · pending lab assistant",
      ownerMeta: "Primary lecturer is confirmed; assistant shortlist is under review.",
      checkpoint: "Review Apr 26, 2026",
      checkpointMeta: "Needs location readiness before the pack can advance.",
      detailItems: [
        "The teaching pack already includes the lecture owner and assessment reviewer.",
        "Assistant assignment is dependent on the data lab reopening after maintenance.",
        "Publishing should wait until the Friday location audit is completed.",
      ],
      searchText: "Data Warehousing Fernando draft",
    },
    {
      id: "assign-cy305",
      category: "FINALIZED",
      title: "CY305 · Secure Network Labs",
      subtitle: "Hands-on lab delivery has confirmed staff and room capacity for the full block.",
      coverage: "FOC · Level 3 · Term 2 · Weekday",
      coverageMeta: "1 lecture block, 2 lab lanes, 64 enrolled students.",
      status: "Finalized",
      statusVariant: "success",
      statusMeta: "The teaching team is complete and room constraints have been cleared.",
      owner: "Dr. S. Nawarathne · 1 lecturer · 2 lab assistants",
      ownerMeta: "Both lab assistants are already synced from the eligible support pool.",
      checkpoint: "Publish Apr 22, 2026",
      checkpointMeta: "Ready to feed the cybersecurity timetable board.",
      detailItems: [
        "Two identical lab groups were created to keep the router equipment load stable.",
        "The LIC is also assigned as the moderation owner for the final practical.",
        "No staff conflicts remain after the latest evening-slot rebalance.",
      ],
      searchText: "Secure Network Labs Nawarathne",
    },
    {
      id: "assign-it118",
      category: "REVIEW",
      title: "IT118 · Computing Foundations",
      subtitle: "Large-cohort teaching coverage needs a final assistant distribution pass.",
      coverage: "FOC · Level 1 · Term 1 · Weekday",
      coverageMeta: "4 lecture blocks, 2 tutorial lanes, 214 enrolled students.",
      status: "Review",
      statusVariant: "warning",
      statusMeta: "Tutorial support is short by one assistant for the second half of term.",
      owner: "Prof. D. Silva · 3 lecturers · 1 assistant assigned",
      ownerMeta: "The teaching lead is fixed, but tutorial ownership still needs adjustment.",
      checkpoint: "Rebalance Apr 27, 2026",
      checkpointMeta: "Escalate if an additional support lane is not secured.",
      detailItems: [
        "The cohort size requires a split between foundation and remedial tutorial flows.",
        "One support lane is covered by a temporary assignment that ends mid-term.",
        "A second review is scheduled after intake transfers are finalized.",
      ],
      searchText: "Computing Foundations Silva large cohort",
    },
    {
      id: "assign-ds420",
      category: "FINALIZED",
      title: "DS420 · Final Year Capstone Supervision",
      subtitle: "Supervisor distribution has been aligned to capstone clusters and review panels.",
      coverage: "FOC · Level 4 · Term 2 · Mixed delivery",
      coverageMeta: "6 supervision clusters, 18 review staff, 52 active projects.",
      status: "Finalized",
      statusVariant: "success",
      statusMeta: "Panel moderation and weekly supervision loads are both confirmed.",
      owner: "Capstone office · 8 supervisors · 10 panel reviewers",
      ownerMeta: "Reviewer allocation is balanced across research and engineering tracks.",
      checkpoint: "Panel brief Apr 29, 2026",
      checkpointMeta: "Ready for assessment and timetable publication.",
      detailItems: [
        "Supervisor-to-project ratios stay within the agreed final-year delivery policy.",
        "Each review panel includes one backup reviewer for absence coverage.",
        "The capstone office will lock the roster after the April 29 briefing.",
      ],
      searchText: "Capstone supervision mixed delivery",
    },
  ],
  boardTitle: "Assignment Coverage Board",
  boardDescription:
    "Review teaching ownership, staffing coverage, and next checkpoints from a cleaner faculty-style management surface.",
  emptyMessage: "No assignment lanes match the current filters.",
  plannerBadge: "Assignment Flow",
  plannerTitle: "Teaching assignment rollout",
  plannerDescription:
    "Use this surface to align staffing decisions before timetable publication and module-offering synchronization are finalized.",
  plannerChecklist: [
    "Confirm LIC ownership, workload balance, and backup coverage for every active offering.",
    "Resolve timetable or location conflicts before pushing assignments downstream.",
    "Keep lecturer and lab assistant decisions visible so approvals do not leave the Teaching section.",
  ],
};

export const subgroupAllocationConfig: TeachingWorkspaceConfig = {
  sectionLabel,
  title: "Subgroup allocation",
  description:
    "Review subgroup distribution, manual exceptions, and sync readiness from the same structured UI language used by the updated Faculties page.",
  visibleDescription: "Showing the subgroup workspaces currently staged for review or lock.",
  actionLabel: "Open Allocation Brief",
  actionIcon: GitBranchPlus,
  searchPlaceholder: "Search by intake, level, or subgroup coordinator",
  filterLabel: "Allocation state",
  filterOptions: [
    { label: "All states", value: "" },
    { label: "Synced", value: "SYNCED" },
    { label: "Review", value: "REVIEW" },
    { label: "Locked", value: "LOCKED" },
  ],
  highlights: [
    "Allocation packs keep student counts, subgroup balance, and tutor coverage in one scan.",
    "Manual exceptions remain visible instead of being buried inside later timetable adjustments.",
    "The page now follows the same strong card and table system already used in Academics.",
  ],
  summaryCards: [
    {
      label: "Active Cohorts",
      value: "9",
      detail: "Intake and level combinations actively managed in the subgroup pipeline.",
      tone: "teal",
      icon: Users,
    },
    {
      label: "Balanced Groups",
      value: "24",
      detail: "Subgroups already within the preferred variance threshold.",
      tone: "green",
      icon: CheckCircle2,
    },
    {
      label: "Manual Exceptions",
      value: "7",
      detail: "Transfers, repeats, and advisor requests still awaiting coordinator action.",
      tone: "amber",
      icon: AlertTriangle,
    },
    {
      label: "Latest Sync",
      value: "Today",
      detail: "Allocation snapshots were refreshed from the latest intake roster.",
      tone: "sky",
      icon: Clock3,
    },
  ],
  rows: [
    {
      id: "alloc-se-2026-1",
      category: "SYNCED",
      title: "2026.1 · Software Engineering Level 1",
      subtitle: "Core subgroup distribution is synced and ready to feed timetable and coursework views.",
      coverage: "148 students · 4 subgroups · Weekday",
      coverageMeta: "Balance variance stays under three students per subgroup.",
      status: "Synced",
      statusVariant: "success",
      statusMeta: "No unresolved overrides remain in the primary delivery lane.",
      owner: "2 tutors · 1 coordinator",
      ownerMeta: "Tutor assignments are aligned to the intake advisory structure.",
      checkpoint: "Lock Apr 26, 2026",
      checkpointMeta: "Prepared for downstream synchronization after final review.",
      detailItems: [
        "Student distribution already accounts for repeat modules and stream preference.",
        "Tutorial ownership has been aligned so each subgroup keeps a consistent contact point.",
        "The lock will proceed automatically if no additional transfers land before the cutoff.",
      ],
      searchText: "Software Engineering Level 1 synced weekday",
    },
    {
      id: "alloc-is-2026-1",
      category: "REVIEW",
      title: "2026.1 · Information Systems Level 2",
      subtitle: "A small set of transfer students still needs manual placement before the pack can lock.",
      coverage: "96 students · 3 subgroups · Weekday",
      coverageMeta: "Two manual move requests are open after late registration changes.",
      status: "Review",
      statusVariant: "warning",
      statusMeta: "Advisor requests are holding the final subgroup balance review.",
      owner: "1 coordinator · 3 subgroup mentors",
      ownerMeta: "Mentor capacity is available, but one subgroup exceeds the target size.",
      checkpoint: "Review Apr 23, 2026",
      checkpointMeta: "Manual placements must close before timetable sync.",
      detailItems: [
        "The late-transfer students must stay aligned to the same practical lab window.",
        "One subgroup can absorb two students without exceeding the balance target.",
        "Coordinator approval will determine whether a fourth subgroup is necessary.",
      ],
      searchText: "Information Systems Level 2 review transfers",
    },
    {
      id: "alloc-cy-2025-2",
      category: "LOCKED",
      title: "2025.2 · Cybersecurity Level 3",
      subtitle: "Advanced lab cohorts are locked and already referenced by timetable and assessment boards.",
      coverage: "62 students · 2 subgroups · Mixed delivery",
      coverageMeta: "Each subgroup is tied to a separate practical security lab.",
      status: "Locked",
      statusVariant: "primary",
      statusMeta: "No further movement is allowed without academic office approval.",
      owner: "Program office · 2 lab tutors",
      ownerMeta: "Tutor pairings remain stable through the full assessment window.",
      checkpoint: "Audit Apr 30, 2026",
      checkpointMeta: "Next check is limited to attendance and retention drift.",
      detailItems: [
        "Both subgroups already map to separate room reservations and equipment bundles.",
        "Locked status ensures assessment deadlines stay aligned to the published plan.",
        "Any future move request must go through the academic office override flow.",
      ],
      searchText: "Cybersecurity locked lab cohorts",
    },
    {
      id: "alloc-ds-2026-1",
      category: "SYNCED",
      title: "2026.1 · Data Science Level 1",
      subtitle: "Foundational subgroup allocation is healthy and ready for teaching publication.",
      coverage: "132 students · 4 subgroups · Weekday",
      coverageMeta: "Even spread across math-support and core-programming pathways.",
      status: "Synced",
      statusVariant: "success",
      statusMeta: "The current draft already meets both size and support constraints.",
      owner: "1 coordinator · 4 advisors",
      ownerMeta: "Advisor coverage mirrors the weekly foundation support plan.",
      checkpoint: "Publish Apr 25, 2026",
      checkpointMeta: "Moves to timetable once the final intake list is frozen.",
      detailItems: [
        "The subgroup set separates students needing additional foundation support.",
        "Each advisor is assigned to a single subgroup to keep escalation paths clear.",
        "Only roster finalization remains before the workspace is published.",
      ],
      searchText: "Data Science Level 1 subgroup publish",
    },
    {
      id: "alloc-it-2025-3",
      category: "REVIEW",
      title: "2025.3 · Information Technology Level 3 Weekend",
      subtitle: "Weekend delivery needs a second pass because one subgroup is overloaded after deferrals.",
      coverage: "88 students · 2 subgroups · Weekend",
      coverageMeta: "One subgroup currently exceeds the preferred cap by six students.",
      status: "Review",
      statusVariant: "warning",
      statusMeta: "Balance remediation is still pending before the pack can lock.",
      owner: "Weekend office · 2 tutors",
      ownerMeta: "Tutor capacity allows a split if a third subgroup is approved.",
      checkpoint: "Decision Apr 24, 2026",
      checkpointMeta: "Waiting on approval for a temporary third subgroup.",
      detailItems: [
        "Weekend availability narrows the set of tutors who can absorb a new group.",
        "A third subgroup would reduce pressure on the overloaded practical lane.",
        "If the request is rejected, additional tutorial support will be needed instead.",
      ],
      searchText: "Information Technology weekend review overloaded",
    },
    {
      id: "alloc-se-2025-2",
      category: "LOCKED",
      title: "2025.2 · Software Engineering Level 4 Project Labs",
      subtitle: "Project-lab subgroups are fixed for the remainder of the semester.",
      coverage: "54 students · 3 subgroups · Mixed delivery",
      coverageMeta: "Project supervision clusters already mirror the locked subgroup map.",
      status: "Locked",
      statusVariant: "primary",
      statusMeta: "Changes are disabled because project review panels are already published.",
      owner: "Project office · 6 supervisors",
      ownerMeta: "Supervisor loads remain within the agreed project-lab threshold.",
      checkpoint: "Monitor May 02, 2026",
      checkpointMeta: "Only project attrition would trigger another review.",
      detailItems: [
        "The locked set keeps each project cluster intact across delivery and assessment.",
        "Review panel assignments already depend on this subgroup structure.",
        "The next touchpoint is operational monitoring rather than reallocation.",
      ],
      searchText: "Software Engineering project labs locked",
    },
  ],
  boardTitle: "Allocation Review Board",
  boardDescription:
    "Track subgroup balance, manual overrides, and locking decisions inside a consistent management table.",
  emptyMessage: "No allocation workspaces match the current filters.",
  plannerBadge: "Allocation Flow",
  plannerTitle: "Subgroup allocation checkpoints",
  plannerDescription:
    "This workspace keeps the allocation review loop visible before schedules and assessment rules inherit subgroup changes.",
  plannerChecklist: [
    "Resolve late registrations, transfers, and advisor overrides before locking the cohort.",
    "Keep subgroup balance visible so teaching and timetable changes do not diverge later.",
    "Use the locked state only after timetable and assessment dependencies are safe to publish.",
  ],
};

export const timetableConfig: TeachingWorkspaceConfig = {
  sectionLabel,
  title: "Timetable",
  description:
    "Manage draft, review, and published schedule boards with the same polished cards, filters, and table hierarchy used by the Faculties screen.",
  visibleDescription: "Showing the timetable boards currently staged for review and publication.",
  actionLabel: "Open Scheduling Brief",
  actionIcon: CalendarRange,
  searchPlaceholder: "Search by board, intake, stream, or publication owner",
  filterLabel: "Board status",
  filterOptions: [
    { label: "All boards", value: "" },
    { label: "Published", value: "PUBLISHED" },
    { label: "Review", value: "REVIEW" },
    { label: "Draft", value: "DRAFT" },
  ],
  highlights: [
    "Schedule boards now read like a proper operational workspace instead of a generic placeholder.",
    "Publication state, room readiness, and staff coverage are visible in one faculty-style table.",
    "This layout is ready for live timetable data without another UI reset later.",
  ],
  summaryCards: [
    {
      label: "Weekly Boards",
      value: "11",
      detail: "Active scheduling boards managed across weekday, weekend, and mixed delivery.",
      tone: "teal",
      icon: CalendarRange,
    },
    {
      label: "Published",
      value: "7",
      detail: "Boards already cleared for student and staff visibility.",
      tone: "green",
      icon: CheckCircle2,
    },
    {
      label: "Collision Checks",
      value: "3",
      detail: "Open room or lecturer overlaps still need coordinator action.",
      tone: "amber",
      icon: AlertTriangle,
    },
    {
      label: "Next Release",
      value: "Apr 24",
      detail: "Upcoming publication window for draft boards under final review.",
      tone: "sky",
      icon: Clock3,
    },
  ],
  rows: [
    {
      id: "tt-l1-weekday",
      category: "PUBLISHED",
      title: "FOC Level 1 · Weekday Board",
      subtitle: "The full foundation schedule is published and already aligned to subgroup and room constraints.",
      coverage: "26 teaching blocks · Mon to Fri",
      coverageMeta: "Lecture halls, tutorials, and foundation labs are all locked for the week.",
      status: "Published",
      statusVariant: "success",
      statusMeta: "Students and staff can already consume the current board version.",
      owner: "12 rooms · 18 staff members",
      ownerMeta: "Coverage includes overflow rooms for the larger core modules.",
      checkpoint: "Refresh Apr 28, 2026",
      checkpointMeta: "Only late enrollment changes are expected before the next release.",
      detailItems: [
        "The board already references the latest subgroup allocation snapshot.",
        "Overflow rooms were reserved for the two highest-enrollment modules.",
        "The next refresh should only absorb minor roster changes rather than structural edits.",
      ],
      searchText: "Level 1 weekday board published",
    },
    {
      id: "tt-l2-weekend",
      category: "REVIEW",
      title: "FOC Level 2 · Weekend Board",
      subtitle: "Weekend scheduling is under review because one lecturer conflict remains unresolved.",
      coverage: "14 teaching blocks · Sat to Sun",
      coverageMeta: "Weekend delivery spans lecture halls, one lab, and advisor support windows.",
      status: "Review",
      statusVariant: "warning",
      statusMeta: "A single lecturer overlap is blocking board publication.",
      owner: "6 rooms · 9 staff members",
      ownerMeta: "Room coverage is confirmed; only staff timing needs correction.",
      checkpoint: "Resolve Apr 23, 2026",
      checkpointMeta: "Publish immediately after the conflict is closed.",
      detailItems: [
        "The open conflict is limited to one lecturer handling two adjacent weekend sessions.",
        "A backup lecturer is available if the preferred change is not approved in time.",
        "No room or equipment issue remains on the weekend board.",
      ],
      searchText: "Level 2 weekend review lecturer overlap",
    },
    {
      id: "tt-capstone",
      category: "DRAFT",
      title: "Capstone Review Cycle · Term 2",
      subtitle: "The draft board maps supervision clinics and review panels before publication.",
      coverage: "9 review windows · Mixed delivery",
      coverageMeta: "Includes panel blocks, project clinics, and supervisor office hours.",
      status: "Draft",
      statusVariant: "info",
      statusMeta: "Awaiting final panel availability from the project office.",
      owner: "4 seminar rooms · 18 reviewers",
      ownerMeta: "Rooms are penciled in, but reviewer schedules remain provisional.",
      checkpoint: "Approve Apr 29, 2026",
      checkpointMeta: "Panel confirmations must land before the board can move forward.",
      detailItems: [
        "The capstone cycle depends on external reviewers confirming their attendance windows.",
        "Seminar room reservations are soft-held until the panel roster is fixed.",
        "The board will publish in one batch once all reviewers confirm availability.",
      ],
      searchText: "Capstone review cycle draft panels",
    },
    {
      id: "tt-cy-labs",
      category: "PUBLISHED",
      title: "Cybersecurity Labs · Evening Board",
      subtitle: "Evening lab slots are published with stable room, equipment, and staff assignments.",
      coverage: "8 lab blocks · Tue to Thu evenings",
      coverageMeta: "Covers practical labs, demo windows, and debrief sessions.",
      status: "Published",
      statusVariant: "success",
      statusMeta: "The board is already visible and collision-free.",
      owner: "2 secure labs · 5 delivery staff",
      ownerMeta: "Lab assistants are tied to the same rooms for the full cycle.",
      checkpoint: "Audit Apr 30, 2026",
      checkpointMeta: "Only equipment readiness will be re-checked before the next cycle.",
      detailItems: [
        "Evening slots were spaced to avoid clashes with daytime foundation labs.",
        "Assistant assignments remain fixed to preserve continuity across practical assessments.",
        "The next checkpoint focuses on equipment status rather than scheduling drift.",
      ],
      searchText: "Cybersecurity labs evening published",
    },
    {
      id: "tt-ds-weekday",
      category: "REVIEW",
      title: "Data Science Level 1 · Weekday Board",
      subtitle: "The foundational board is nearly ready but still depends on one room capacity adjustment.",
      coverage: "22 teaching blocks · Mon to Fri",
      coverageMeta: "Math support, labs, and programming lectures share a coordinated weekly board.",
      status: "Review",
      statusVariant: "warning",
      statusMeta: "A large lecture is waiting on a room swap for final publication.",
      owner: "9 rooms · 14 staff members",
      ownerMeta: "Staff assignments are final, but the room matrix needs one update.",
      checkpoint: "Swap Apr 24, 2026",
      checkpointMeta: "Publish after the new hall reservation is confirmed.",
      detailItems: [
        "The current lecture hall cannot absorb the late intake increase safely.",
        "A larger hall is tentatively available without changing the rest of the board.",
        "Once the swap is confirmed, the timetable can move straight to published state.",
      ],
      searchText: "Data Science weekday room swap review",
    },
    {
      id: "tt-business-weekend",
      category: "DRAFT",
      title: "Cross-Faculty Business Electives · Weekend",
      subtitle: "A draft timetable board is being assembled for shared elective delivery.",
      coverage: "10 teaching blocks · Weekend mix",
      coverageMeta: "Shared electives pull staff from multiple faculties and common rooms.",
      status: "Draft",
      statusVariant: "info",
      statusMeta: "The board is still assembling common-room and lecturer availability.",
      owner: "5 shared spaces · 7 staff members",
      ownerMeta: "Cross-faculty ownership requires one final coordination pass.",
      checkpoint: "Draft review Apr 27, 2026",
      checkpointMeta: "Ready for board-level review once all shared resources are confirmed.",
      detailItems: [
        "Cross-faculty ownership is the main blocker because shared rooms remain contested.",
        "The current draft already respects the common elective assessment calendar.",
        "The board will move quickly once the shared-room allocations are finalized.",
      ],
      searchText: "Business electives weekend cross faculty",
    },
  ],
  boardTitle: "Timetable Publishing Board",
  boardDescription:
    "Track schedule readiness, publication state, and open collisions from a consistent operational board.",
  emptyMessage: "No timetable boards match the current filters.",
  plannerBadge: "Scheduling Flow",
  plannerTitle: "Timetable publication checkpoints",
  plannerDescription:
    "Keep the schedule release path visible so room, staffing, and publication approvals move through one clean workspace.",
  plannerChecklist: [
    "Clear lecturer and room collisions before a board moves from review to published.",
    "Keep weekday, weekend, and mixed-delivery boards visible with separate publication states.",
    "Use the review lane to absorb room-capacity and late-intake changes before releasing updates.",
  ],
};

export const locationsConfig: TeachingWorkspaceConfig = {
  sectionLabel,
  title: "Locations / labs",
  description:
    "Track room readiness, lab maintenance, and reservation pressure using the same admin UI system that already powers the Faculties page.",
  visibleDescription: "Showing the teaching spaces currently monitored for readiness or hold status.",
  actionLabel: "Open Space Brief",
  actionIcon: Building2,
  searchPlaceholder: "Search by room, lab type, faculty, or coordinator",
  filterLabel: "Availability",
  filterOptions: [
    { label: "All spaces", value: "" },
    { label: "Available", value: "AVAILABLE" },
    { label: "Reserved", value: "RESERVED" },
    { label: "Maintenance", value: "MAINTENANCE" },
  ],
  highlights: [
    "Locations now sit inside a proper teaching workspace instead of a generic in-progress card.",
    "Capacity, equipment readiness, and blackout windows can be scanned from one board.",
    "The visual language stays consistent with Academics so the admin surface feels intentional.",
  ],
  summaryCards: [
    {
      label: "Active Spaces",
      value: "21",
      detail: "Teaching rooms and labs currently staged for the next scheduling cycle.",
      tone: "teal",
      icon: Building2,
    },
    {
      label: "Lab Rooms",
      value: "8",
      detail: "Practical teaching spaces with managed equipment and access controls.",
      tone: "violet",
      icon: Layers3,
    },
    {
      label: "Maintenance Holds",
      value: "3",
      detail: "Spaces temporarily excluded from assignment and timetable publication.",
      tone: "amber",
      icon: AlertTriangle,
    },
    {
      label: "Next Audit",
      value: "Apr 27",
      detail: "Planned readiness review for labs with high scheduling pressure.",
      tone: "sky",
      icon: MapPin,
    },
  ],
  rows: [
    {
      id: "loc-netlab-03",
      category: "AVAILABLE",
      title: "Network Lab 03",
      subtitle: "Primary cybersecurity lab with full router kit and secure-image support.",
      coverage: "42 seats · secure networking equipment",
      coverageMeta: "Reserved for evening and advanced practical sessions.",
      status: "Available",
      statusVariant: "success",
      statusMeta: "Room is clean for assignment and timetable publication.",
      owner: "FOC operations · Cybersecurity teaching lane",
      ownerMeta: "Current setup matches the secure-lab delivery requirements.",
      checkpoint: "Inspect Apr 28, 2026",
      checkpointMeta: "Routine audit only; no blockers are currently open.",
      detailItems: [
        "All router and switch kits were reimaged during the last maintenance window.",
        "The space is configured to support parallel lab groups without extra equipment load.",
        "Only a routine readiness audit remains before the next high-demand cycle.",
      ],
      searchText: "Network Lab 03 cybersecurity available",
    },
    {
      id: "loc-b204",
      category: "RESERVED",
      title: "Seminar Room B204",
      subtitle: "Medium-capacity seminar space reserved for capstone reviews and advisory clinics.",
      coverage: "28 seats · projector · hybrid support",
      coverageMeta: "Reserved across three review windows during the current capstone cycle.",
      status: "Reserved",
      statusVariant: "primary",
      statusMeta: "Space is healthy but locked against general timetable use for now.",
      owner: "Project office · review panel schedule",
      ownerMeta: "Reservations align to capstone review and consultation demand.",
      checkpoint: "Release Apr 30, 2026",
      checkpointMeta: "General scheduling can resume after the capstone window closes.",
      detailItems: [
        "The room remains reserved because review panels need consistent hybrid support.",
        "Outside bookings are blocked to avoid fragmenting the capstone cycle.",
        "The room should reopen immediately after the final review panel completes.",
      ],
      searchText: "Seminar Room B204 reserved capstone",
    },
    {
      id: "loc-hwlab-02",
      category: "MAINTENANCE",
      title: "Hardware Lab 02",
      subtitle: "The room is temporarily unavailable while workstation imaging and seating repairs finish.",
      coverage: "30 seats · hardware benches · imaging bay",
      coverageMeta: "The lab is excluded from new timetable allocations until repairs are closed.",
      status: "Maintenance",
      statusVariant: "warning",
      statusMeta: "Active hold prevents teaching assignments from targeting this lab.",
      owner: "Facilities team · lab operations",
      ownerMeta: "Repair work includes bench power checks and workstation refreshes.",
      checkpoint: "Reopen Apr 26, 2026",
      checkpointMeta: "Pending final sign-off from facilities and lab support.",
      detailItems: [
        "Bench power modules failed during the previous intensive practical cycle.",
        "Workstation imaging is already underway and should finish before the reopen date.",
        "The lab will only return to active use after a joint facilities and support audit.",
      ],
      searchText: "Hardware Lab 02 maintenance imaging",
    },
    {
      id: "loc-a1",
      category: "AVAILABLE",
      title: "Lecture Hall A1",
      subtitle: "Large-capacity hall currently preferred for high-enrollment weekday modules.",
      coverage: "180 seats · dual projection · lecture capture",
      coverageMeta: "Frequently used by foundation modules and cross-faculty common lectures.",
      status: "Available",
      statusVariant: "success",
      statusMeta: "The hall is active and clear for the next publication cycle.",
      owner: "Central scheduling · large-cohort teaching",
      ownerMeta: "The current setup supports lecture capture and overflow attendance.",
      checkpoint: "Audit May 01, 2026",
      checkpointMeta: "No issues are open beyond the routine utilization review.",
      detailItems: [
        "The hall is the fallback destination for boards requiring a late capacity upgrade.",
        "Capture tooling was tested and cleared during the previous audit.",
        "Scheduling pressure remains high, but no technical blocker is active.",
      ],
      searchText: "Lecture Hall A1 available large cohort",
    },
    {
      id: "loc-innovation-studio",
      category: "RESERVED",
      title: "Innovation Studio",
      subtitle: "Flexible design studio reserved for workshop-driven teaching and showcase events.",
      coverage: "24 seats · movable layout · critique wall",
      coverageMeta: "Held for studio delivery, project demos, and external review events.",
      status: "Reserved",
      statusVariant: "primary",
      statusMeta: "General release is paused until the current studio block ends.",
      owner: "Design faculty · studio and showcase lane",
      ownerMeta: "Reservations support workshop-heavy teaching methods that need the open layout.",
      checkpoint: "Review Apr 29, 2026",
      checkpointMeta: "Reservation scope may shrink after the showcase schedule is confirmed.",
      detailItems: [
        "The movable layout makes this space unsuitable for fragmented room sharing.",
        "A combined studio and showcase calendar is holding the room for now.",
        "If the showcase footprint shrinks, selected weekday slots can reopen.",
      ],
      searchText: "Innovation Studio reserved showcase",
    },
    {
      id: "loc-media-01",
      category: "MAINTENANCE",
      title: "Multimedia Lab 01",
      subtitle: "Editing stations are under maintenance after graphics-card failures during a peak week.",
      coverage: "26 seats · media workstations · sound booth",
      coverageMeta: "The lab is blocked from new reservations until replacement parts arrive.",
      status: "Maintenance",
      statusVariant: "warning",
      statusMeta: "Teaching use is paused because equipment readiness is below threshold.",
      owner: "Media support · creative labs",
      ownerMeta: "Current focus is GPU replacement and booth sound isolation checks.",
      checkpoint: "Parts due Apr 27, 2026",
      checkpointMeta: "Scheduling remains blocked until repairs are verified on site.",
      detailItems: [
        "Several workstations failed the last rendering stress test and were pulled from service.",
        "Replacement graphics units are scheduled to land before the next audit window.",
        "The room will stay blocked until media staff confirm stable performance under load.",
      ],
      searchText: "Multimedia Lab 01 maintenance GPU",
    },
  ],
  boardTitle: "Location Readiness Board",
  boardDescription:
    "Monitor capacity, reservation pressure, and maintenance status through a consistent teaching operations board.",
  emptyMessage: "No teaching spaces match the current filters.",
  plannerBadge: "Facilities Flow",
  plannerTitle: "Location readiness checkpoints",
  plannerDescription:
    "Keep teaching-space health visible so assignment and timetable teams do not discover room problems too late in the workflow.",
  plannerChecklist: [
    "Track reserved rooms separately from spaces that are genuinely available for new scheduling work.",
    "Keep maintenance holds visible so assignment and timetable reviews do not depend on unavailable labs.",
    "Audit high-pressure spaces early when large cohorts or equipment-heavy modules depend on them.",
  ],
};
